on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: hello
      uses: /path/to/action
      with:
        myInput: 'Pratul Goyal'
    - name: output
      run: |
        echo ${{steps.hello.outputs.myInput}}
        echo "totally memory successfully output"
